name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project 
      uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/votebot/votebot/bot:$(date +%s)
    - name: Login to Docker Registry
      run: docker login docker.pkg.github.com --username Votebot
    - name: Push Docker Image
      run: docker push docker.pkg.github.com/votebot/votebot/bot:$(date +%s)
